# Generated by Django 3.0 on 2021-04-28 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userleave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleave',
            name='user_leave',
            field=models.FloatField(default='0', validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
