# Generated by Django 3.0 on 2021-04-28 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210428_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleave',
            name='user_leave',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.CreateModel(
            name='GetLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_get', models.FloatField(default=0)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Leave')),
            ],
        ),
    ]
